### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by rkovachev88** [velivelo/insta-bot#5]
It is running for 15-30 minutes and then it is crashing - the window is closing itself.

**Comment by velivelo** [comment]
Can you run the code on a console (so the window won't close) and tell me the error message ?

**Comment by rkovachev88** [comment]
> Traceback (most recent call last):
>   File "C:\...\insta-bot-master\src\automod.py", line 67, in start
>     username = self.userIdToUsername(user_id)
>   File "C:\...\insta-bot-master\src\instabot.py", line 134, in userIdToUsername
>     return r.json()["user"]["username"]
> KeyError: 'user'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\...\insta-bot-master\src\automod.py", line 140, in <module>
>     "end_at": datetime.time(hour=23, minute=15),
>   File "C:\...\insta-bot-master\src\automod.py", line 126, in start
>     sys.stdout("{} Error {}".format(formatedDate(), e))
> TypeError: '_io.TextIOWrapper' object is not callable

**Comment by rkovachev88** [comment]
Another one after the new code:

```
Traceback (most recent call last):
  File "C:\...\insta-bot-master\src\automod-new.py", line 86, in start
    media_owner = self.getUserDetails(self.userIdToUsername(media["owner"]["id"]))
  File "C:\...\insta-bot-master\src\instabot.py", line 134, in userIdToUsername
    return r.json()["user"]["username"]
KeyError: 'user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\...\insta-bot-master\src\automod-new.py", line 143, in <module>
    "end_at": datetime.time(hour=23, minute=15),
  File "C:\...\insta-bot-master\src\automod-new.py", line 129, in start
    sys.stdout("{} Error {}".format(formatedDate(), e))
TypeError: '_io.TextIOWrapper' object is not callable
```

**Comment by rkovachev88** [comment]
New one:

```
C:\...\insta-bot-master\src>automod.py
  File "C:\...\insta-bot-master\src\automod.py", line 88
    except KeyError:
                   ^
IndentationError: unindent does not match any outer indentation level
```

**Comment by rkovachev88** [comment]
It is more stable now, but I have this error:

```
12:00:00 400 Client Error: Bad Request for url: https://www.instagram.com/web/likes/1771709753156756038/like/
Traceback (most recent call last):
  File "C:\...\insta-bot-master\src\automod-88.py", line 81, in start
    for media in self.explore(random.choice(tags))[:max_stack_size]:
  File "C:\...\AppData\Local\Programs\Python\Python36\lib\random.py", line 259, in choice
    return seq[i]
KeyError: 14

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\...\insta-bot-master\src\automod-88.py", line 146, in <module>
    "end_at": datetime.time(hour=23, minute=15),
  File "C:\...\insta-bot-master\src\automod-88.py", line 137, in start
    self.start(saved_args)
  File "C:\...\insta-bot-master\src\automod-88.py", line 132, in start
    sys.stdout("{} Error {}".format(formatedDate(), e))
TypeError: '_io.TextIOWrapper' object is not callable
```
